#pragma warning disable 1591
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace bananhhao.Models
{
	using System.Data.Linq;
	using System.Data.Linq.Mapping;
	using System.Data;
	using System.Collections.Generic;
	using System.Reflection;
	using System.Linq;
	using System.Linq.Expressions;
	using System.ComponentModel;
	using System;
	
	
	[global::System.Data.Linq.Mapping.DatabaseAttribute(Name="thuctap")]
	public partial class DataClasses1DataContext : System.Data.Linq.DataContext
	{
		
		private static System.Data.Linq.Mapping.MappingSource mappingSource = new AttributeMappingSource();
		
    #region Extensibility Method Definitions
    partial void OnCreated();
    partial void Insertcthoadon(cthoadon instance);
    partial void Updatecthoadon(cthoadon instance);
    partial void Deletecthoadon(cthoadon instance);
    partial void Insertkhachhang(khachhang instance);
    partial void Updatekhachhang(khachhang instance);
    partial void Deletekhachhang(khachhang instance);
    partial void Insertdienke(dienke instance);
    partial void Updatedienke(dienke instance);
    partial void Deletedienke(dienke instance);
    partial void Insertgiadien(giadien instance);
    partial void Updategiadien(giadien instance);
    partial void Deletegiadien(giadien instance);
    partial void Inserthoadon(hoadon instance);
    partial void Updatehoadon(hoadon instance);
    partial void Deletehoadon(hoadon instance);
    #endregion
		
		public DataClasses1DataContext() : 
				base(global::System.Configuration.ConfigurationManager.ConnectionStrings["thuctapConnectionString1"].ConnectionString, mappingSource)
		{
			OnCreated();
		}
		
		public DataClasses1DataContext(string connection) : 
				base(connection, mappingSource)
		{
			OnCreated();
		}
		
		public DataClasses1DataContext(System.Data.IDbConnection connection) : 
				base(connection, mappingSource)
		{
			OnCreated();
		}
		
		public DataClasses1DataContext(string connection, System.Data.Linq.Mapping.MappingSource mappingSource) : 
				base(connection, mappingSource)
		{
			OnCreated();
		}
		
		public DataClasses1DataContext(System.Data.IDbConnection connection, System.Data.Linq.Mapping.MappingSource mappingSource) : 
				base(connection, mappingSource)
		{
			OnCreated();
		}
		
		public System.Data.Linq.Table<cthoadon> cthoadons
		{
			get
			{
				return this.GetTable<cthoadon>();
			}
		}
		
		public System.Data.Linq.Table<khachhang> khachhangs
		{
			get
			{
				return this.GetTable<khachhang>();
			}
		}
		
		public System.Data.Linq.Table<dienke> dienkes
		{
			get
			{
				return this.GetTable<dienke>();
			}
		}
		
		public System.Data.Linq.Table<giadien> giadiens
		{
			get
			{
				return this.GetTable<giadien>();
			}
		}
		
		public System.Data.Linq.Table<hoadon> hoadons
		{
			get
			{
				return this.GetTable<hoadon>();
			}
		}
		
		[global::System.Data.Linq.Mapping.FunctionAttribute(Name="dbo.TinhDienNangTieuThu")]
		public int TinhDienNangTieuThu([global::System.Data.Linq.Mapping.ParameterAttribute(DbType="Int")] System.Nullable<int> chisocuoi)
		{
			IExecuteResult result = this.ExecuteMethodCall(this, ((MethodInfo)(MethodInfo.GetCurrentMethod())), chisocuoi);
			return ((int)(result.ReturnValue));
		}
		
		[global::System.Data.Linq.Mapping.FunctionAttribute(Name="dbo.laphoadon")]
		public int laphoadon([global::System.Data.Linq.Mapping.ParameterAttribute(DbType="Int")] System.Nullable<int> diennangtieuthu, [global::System.Data.Linq.Mapping.ParameterAttribute(DbType="Float")] System.Nullable<double> tiendien, [global::System.Data.Linq.Mapping.ParameterAttribute(DbType="VarChar(13)")] string makh, [global::System.Data.Linq.Mapping.ParameterAttribute(DbType="VarChar(10)")] string mahd, [global::System.Data.Linq.Mapping.ParameterAttribute(DbType="Int")] System.Nullable<int> chisocuoi)
		{
			IExecuteResult result = this.ExecuteMethodCall(this, ((MethodInfo)(MethodInfo.GetCurrentMethod())), diennangtieuthu, tiendien, makh, mahd, chisocuoi);
			return ((int)(result.ReturnValue));
		}
		
		[global::System.Data.Linq.Mapping.FunctionAttribute(Name="dbo.getDSKHChuaDongTien")]
		public ISingleResult<getDSKHChuaDongTienResult> getDSKHChuaDongTien()
		{
			IExecuteResult result = this.ExecuteMethodCall(this, ((MethodInfo)(MethodInfo.GetCurrentMethod())));
			return ((ISingleResult<getDSKHChuaDongTienResult>)(result.ReturnValue));
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.cthoadon")]
	public partial class cthoadon : INotifyPropertyChanging, INotifyPropertyChanged
	{
		
		private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
		
		private string _mahd;
		
		private string _madk;
		
		private System.Nullable<int> _dntt;
		
		private System.Nullable<decimal> _dongia;
		
		private EntityRef<dienke> _dienke;
		
		private EntityRef<hoadon> _hoadon;
		
    #region Extensibility Method Definitions
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void OnmahdChanging(string value);
    partial void OnmahdChanged();
    partial void OnmadkChanging(string value);
    partial void OnmadkChanged();
    partial void OndnttChanging(System.Nullable<int> value);
    partial void OndnttChanged();
    partial void OndongiaChanging(System.Nullable<decimal> value);
    partial void OndongiaChanged();
    #endregion
		
		public cthoadon()
		{
			this._dienke = default(EntityRef<dienke>);
			this._hoadon = default(EntityRef<hoadon>);
			OnCreated();
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_mahd", DbType="VarChar(10) NOT NULL", CanBeNull=false, IsPrimaryKey=true)]
		public string mahd
		{
			get
			{
				return this._mahd;
			}
			set
			{
				if ((this._mahd != value))
				{
					if (this._hoadon.HasLoadedOrAssignedValue)
					{
						throw new System.Data.Linq.ForeignKeyReferenceAlreadyHasValueException();
					}
					this.OnmahdChanging(value);
					this.SendPropertyChanging();
					this._mahd = value;
					this.SendPropertyChanged("mahd");
					this.OnmahdChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_madk", DbType="VarChar(8) NOT NULL", CanBeNull=false, IsPrimaryKey=true)]
		public string madk
		{
			get
			{
				return this._madk;
			}
			set
			{
				if ((this._madk != value))
				{
					if (this._dienke.HasLoadedOrAssignedValue)
					{
						throw new System.Data.Linq.ForeignKeyReferenceAlreadyHasValueException();
					}
					this.OnmadkChanging(value);
					this.SendPropertyChanging();
					this._madk = value;
					this.SendPropertyChanged("madk");
					this.OnmadkChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_dntt", DbType="Int")]
		public System.Nullable<int> dntt
		{
			get
			{
				return this._dntt;
			}
			set
			{
				if ((this._dntt != value))
				{
					this.OndnttChanging(value);
					this.SendPropertyChanging();
					this._dntt = value;
					this.SendPropertyChanged("dntt");
					this.OndnttChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_dongia", DbType="Money")]
		public System.Nullable<decimal> dongia
		{
			get
			{
				return this._dongia;
			}
			set
			{
				if ((this._dongia != value))
				{
					this.OndongiaChanging(value);
					this.SendPropertyChanging();
					this._dongia = value;
					this.SendPropertyChanged("dongia");
					this.OndongiaChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="dienke_cthoadon", Storage="_dienke", ThisKey="madk", OtherKey="madk", IsForeignKey=true)]
		public dienke dienke
		{
			get
			{
				return this._dienke.Entity;
			}
			set
			{
				dienke previousValue = this._dienke.Entity;
				if (((previousValue != value) 
							|| (this._dienke.HasLoadedOrAssignedValue == false)))
				{
					this.SendPropertyChanging();
					if ((previousValue != null))
					{
						this._dienke.Entity = null;
						previousValue.cthoadons.Remove(this);
					}
					this._dienke.Entity = value;
					if ((value != null))
					{
						value.cthoadons.Add(this);
						this._madk = value.madk;
					}
					else
					{
						this._madk = default(string);
					}
					this.SendPropertyChanged("dienke");
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="hoadon_cthoadon", Storage="_hoadon", ThisKey="mahd", OtherKey="mahd", IsForeignKey=true)]
		public hoadon hoadon
		{
			get
			{
				return this._hoadon.Entity;
			}
			set
			{
				hoadon previousValue = this._hoadon.Entity;
				if (((previousValue != value) 
							|| (this._hoadon.HasLoadedOrAssignedValue == false)))
				{
					this.SendPropertyChanging();
					if ((previousValue != null))
					{
						this._hoadon.Entity = null;
						previousValue.cthoadons.Remove(this);
					}
					this._hoadon.Entity = value;
					if ((value != null))
					{
						value.cthoadons.Add(this);
						this._mahd = value.mahd;
					}
					else
					{
						this._mahd = default(string);
					}
					this.SendPropertyChanged("hoadon");
				}
			}
		}
		
		public event PropertyChangingEventHandler PropertyChanging;
		
		public event PropertyChangedEventHandler PropertyChanged;
		
		protected virtual void SendPropertyChanging()
		{
			if ((this.PropertyChanging != null))
			{
				this.PropertyChanging(this, emptyChangingEventArgs);
			}
		}
		
		protected virtual void SendPropertyChanged(String propertyName)
		{
			if ((this.PropertyChanged != null))
			{
				this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.khachhang")]
	public partial class khachhang : INotifyPropertyChanging, INotifyPropertyChanged
	{
		
		private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
		
		private string _makh;
		
		private string _tenkh;
		
		private string _diachi;
		
		private string _dt;
		
		private string _cmnd;
		
		private EntitySet<dienke> _dienkes;
		
    #region Extensibility Method Definitions
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void OnmakhChanging(string value);
    partial void OnmakhChanged();
    partial void OntenkhChanging(string value);
    partial void OntenkhChanged();
    partial void OndiachiChanging(string value);
    partial void OndiachiChanged();
    partial void OndtChanging(string value);
    partial void OndtChanged();
    partial void OncmndChanging(string value);
    partial void OncmndChanged();
    #endregion
		
		public khachhang()
		{
			this._dienkes = new EntitySet<dienke>(new Action<dienke>(this.attach_dienkes), new Action<dienke>(this.detach_dienkes));
			OnCreated();
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_makh", DbType="VarChar(13) NOT NULL", CanBeNull=false, IsPrimaryKey=true)]
		public string makh
		{
			get
			{
				return this._makh;
			}
			set
			{
				if ((this._makh != value))
				{
					this.OnmakhChanging(value);
					this.SendPropertyChanging();
					this._makh = value;
					this.SendPropertyChanged("makh");
					this.OnmakhChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_tenkh", DbType="NVarChar(50)")]
		public string tenkh
		{
			get
			{
				return this._tenkh;
			}
			set
			{
				if ((this._tenkh != value))
				{
					this.OntenkhChanging(value);
					this.SendPropertyChanging();
					this._tenkh = value;
					this.SendPropertyChanged("tenkh");
					this.OntenkhChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_diachi", DbType="NVarChar(100)")]
		public string diachi
		{
			get
			{
				return this._diachi;
			}
			set
			{
				if ((this._diachi != value))
				{
					this.OndiachiChanging(value);
					this.SendPropertyChanging();
					this._diachi = value;
					this.SendPropertyChanged("diachi");
					this.OndiachiChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_dt", DbType="NVarChar(12)")]
		public string dt
		{
			get
			{
				return this._dt;
			}
			set
			{
				if ((this._dt != value))
				{
					this.OndtChanging(value);
					this.SendPropertyChanging();
					this._dt = value;
					this.SendPropertyChanged("dt");
					this.OndtChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_cmnd", DbType="VarChar(9)")]
		public string cmnd
		{
			get
			{
				return this._cmnd;
			}
			set
			{
				if ((this._cmnd != value))
				{
					this.OncmndChanging(value);
					this.SendPropertyChanging();
					this._cmnd = value;
					this.SendPropertyChanged("cmnd");
					this.OncmndChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="khachhang_dienke", Storage="_dienkes", ThisKey="makh", OtherKey="makh")]
		public EntitySet<dienke> dienkes
		{
			get
			{
				return this._dienkes;
			}
			set
			{
				this._dienkes.Assign(value);
			}
		}
		
		public event PropertyChangingEventHandler PropertyChanging;
		
		public event PropertyChangedEventHandler PropertyChanged;
		
		protected virtual void SendPropertyChanging()
		{
			if ((this.PropertyChanging != null))
			{
				this.PropertyChanging(this, emptyChangingEventArgs);
			}
		}
		
		protected virtual void SendPropertyChanged(String propertyName)
		{
			if ((this.PropertyChanged != null))
			{
				this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
			}
		}
		
		private void attach_dienkes(dienke entity)
		{
			this.SendPropertyChanging();
			entity.khachhang = this;
		}
		
		private void detach_dienkes(dienke entity)
		{
			this.SendPropertyChanging();
			entity.khachhang = null;
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.dienke")]
	public partial class dienke : INotifyPropertyChanging, INotifyPropertyChanged
	{
		
		private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
		
		private string _madk;
		
		private string _makh;
		
		private System.Nullable<System.DateTime> _ngaysx;
		
		private System.Nullable<System.DateTime> _ngaylap;
		
		private string _mota;
		
		private System.Nullable<bool> _trangthai;
		
		private EntitySet<cthoadon> _cthoadons;
		
		private EntityRef<khachhang> _khachhang;
		
    #region Extensibility Method Definitions
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void OnmadkChanging(string value);
    partial void OnmadkChanged();
    partial void OnmakhChanging(string value);
    partial void OnmakhChanged();
    partial void OnngaysxChanging(System.Nullable<System.DateTime> value);
    partial void OnngaysxChanged();
    partial void OnngaylapChanging(System.Nullable<System.DateTime> value);
    partial void OnngaylapChanged();
    partial void OnmotaChanging(string value);
    partial void OnmotaChanged();
    partial void OntrangthaiChanging(System.Nullable<bool> value);
    partial void OntrangthaiChanged();
    #endregion
		
		public dienke()
		{
			this._cthoadons = new EntitySet<cthoadon>(new Action<cthoadon>(this.attach_cthoadons), new Action<cthoadon>(this.detach_cthoadons));
			this._khachhang = default(EntityRef<khachhang>);
			OnCreated();
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_madk", DbType="VarChar(8) NOT NULL", CanBeNull=false, IsPrimaryKey=true)]
		public string madk
		{
			get
			{
				return this._madk;
			}
			set
			{
				if ((this._madk != value))
				{
					this.OnmadkChanging(value);
					this.SendPropertyChanging();
					this._madk = value;
					this.SendPropertyChanged("madk");
					this.OnmadkChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_makh", DbType="VarChar(13)")]
		public string makh
		{
			get
			{
				return this._makh;
			}
			set
			{
				if ((this._makh != value))
				{
					if (this._khachhang.HasLoadedOrAssignedValue)
					{
						throw new System.Data.Linq.ForeignKeyReferenceAlreadyHasValueException();
					}
					this.OnmakhChanging(value);
					this.SendPropertyChanging();
					this._makh = value;
					this.SendPropertyChanged("makh");
					this.OnmakhChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_ngaysx", DbType="DateTime")]
		public System.Nullable<System.DateTime> ngaysx
		{
			get
			{
				return this._ngaysx;
			}
			set
			{
				if ((this._ngaysx != value))
				{
					this.OnngaysxChanging(value);
					this.SendPropertyChanging();
					this._ngaysx = value;
					this.SendPropertyChanged("ngaysx");
					this.OnngaysxChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_ngaylap", DbType="DateTime")]
		public System.Nullable<System.DateTime> ngaylap
		{
			get
			{
				return this._ngaylap;
			}
			set
			{
				if ((this._ngaylap != value))
				{
					this.OnngaylapChanging(value);
					this.SendPropertyChanging();
					this._ngaylap = value;
					this.SendPropertyChanged("ngaylap");
					this.OnngaylapChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_mota", DbType="NVarChar(100)")]
		public string mota
		{
			get
			{
				return this._mota;
			}
			set
			{
				if ((this._mota != value))
				{
					this.OnmotaChanging(value);
					this.SendPropertyChanging();
					this._mota = value;
					this.SendPropertyChanged("mota");
					this.OnmotaChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_trangthai", DbType="Bit")]
		public System.Nullable<bool> trangthai
		{
			get
			{
				return this._trangthai;
			}
			set
			{
				if ((this._trangthai != value))
				{
					this.OntrangthaiChanging(value);
					this.SendPropertyChanging();
					this._trangthai = value;
					this.SendPropertyChanged("trangthai");
					this.OntrangthaiChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="dienke_cthoadon", Storage="_cthoadons", ThisKey="madk", OtherKey="madk")]
		public EntitySet<cthoadon> cthoadons
		{
			get
			{
				return this._cthoadons;
			}
			set
			{
				this._cthoadons.Assign(value);
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="khachhang_dienke", Storage="_khachhang", ThisKey="makh", OtherKey="makh", IsForeignKey=true)]
		public khachhang khachhang
		{
			get
			{
				return this._khachhang.Entity;
			}
			set
			{
				khachhang previousValue = this._khachhang.Entity;
				if (((previousValue != value) 
							|| (this._khachhang.HasLoadedOrAssignedValue == false)))
				{
					this.SendPropertyChanging();
					if ((previousValue != null))
					{
						this._khachhang.Entity = null;
						previousValue.dienkes.Remove(this);
					}
					this._khachhang.Entity = value;
					if ((value != null))
					{
						value.dienkes.Add(this);
						this._makh = value.makh;
					}
					else
					{
						this._makh = default(string);
					}
					this.SendPropertyChanged("khachhang");
				}
			}
		}
		
		public event PropertyChangingEventHandler PropertyChanging;
		
		public event PropertyChangedEventHandler PropertyChanged;
		
		protected virtual void SendPropertyChanging()
		{
			if ((this.PropertyChanging != null))
			{
				this.PropertyChanging(this, emptyChangingEventArgs);
			}
		}
		
		protected virtual void SendPropertyChanged(String propertyName)
		{
			if ((this.PropertyChanged != null))
			{
				this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
			}
		}
		
		private void attach_cthoadons(cthoadon entity)
		{
			this.SendPropertyChanging();
			entity.dienke = this;
		}
		
		private void detach_cthoadons(cthoadon entity)
		{
			this.SendPropertyChanging();
			entity.dienke = null;
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.giadien")]
	public partial class giadien : INotifyPropertyChanging, INotifyPropertyChanged
	{
		
		private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
		
		private int _mabac;
		
		private string _tenbac;
		
		private System.Nullable<int> _tusokw;
		
		private System.Nullable<int> _densokw;
		
		private System.Nullable<decimal> _dongia;
		
		private System.Nullable<System.DateTime> _ngayapdung;
		
    #region Extensibility Method Definitions
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void OnmabacChanging(int value);
    partial void OnmabacChanged();
    partial void OntenbacChanging(string value);
    partial void OntenbacChanged();
    partial void OntusokwChanging(System.Nullable<int> value);
    partial void OntusokwChanged();
    partial void OndensokwChanging(System.Nullable<int> value);
    partial void OndensokwChanged();
    partial void OndongiaChanging(System.Nullable<decimal> value);
    partial void OndongiaChanged();
    partial void OnngayapdungChanging(System.Nullable<System.DateTime> value);
    partial void OnngayapdungChanged();
    #endregion
		
		public giadien()
		{
			OnCreated();
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_mabac", DbType="Int NOT NULL", IsPrimaryKey=true)]
		public int mabac
		{
			get
			{
				return this._mabac;
			}
			set
			{
				if ((this._mabac != value))
				{
					this.OnmabacChanging(value);
					this.SendPropertyChanging();
					this._mabac = value;
					this.SendPropertyChanged("mabac");
					this.OnmabacChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_tenbac", DbType="NVarChar(50)")]
		public string tenbac
		{
			get
			{
				return this._tenbac;
			}
			set
			{
				if ((this._tenbac != value))
				{
					this.OntenbacChanging(value);
					this.SendPropertyChanging();
					this._tenbac = value;
					this.SendPropertyChanged("tenbac");
					this.OntenbacChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_tusokw", DbType="Int")]
		public System.Nullable<int> tusokw
		{
			get
			{
				return this._tusokw;
			}
			set
			{
				if ((this._tusokw != value))
				{
					this.OntusokwChanging(value);
					this.SendPropertyChanging();
					this._tusokw = value;
					this.SendPropertyChanged("tusokw");
					this.OntusokwChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_densokw", DbType="Int")]
		public System.Nullable<int> densokw
		{
			get
			{
				return this._densokw;
			}
			set
			{
				if ((this._densokw != value))
				{
					this.OndensokwChanging(value);
					this.SendPropertyChanging();
					this._densokw = value;
					this.SendPropertyChanged("densokw");
					this.OndensokwChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_dongia", DbType="Money")]
		public System.Nullable<decimal> dongia
		{
			get
			{
				return this._dongia;
			}
			set
			{
				if ((this._dongia != value))
				{
					this.OndongiaChanging(value);
					this.SendPropertyChanging();
					this._dongia = value;
					this.SendPropertyChanged("dongia");
					this.OndongiaChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_ngayapdung", DbType="DateTime")]
		public System.Nullable<System.DateTime> ngayapdung
		{
			get
			{
				return this._ngayapdung;
			}
			set
			{
				if ((this._ngayapdung != value))
				{
					this.OnngayapdungChanging(value);
					this.SendPropertyChanging();
					this._ngayapdung = value;
					this.SendPropertyChanged("ngayapdung");
					this.OnngayapdungChanged();
				}
			}
		}
		
		public event PropertyChangingEventHandler PropertyChanging;
		
		public event PropertyChangedEventHandler PropertyChanged;
		
		protected virtual void SendPropertyChanging()
		{
			if ((this.PropertyChanging != null))
			{
				this.PropertyChanging(this, emptyChangingEventArgs);
			}
		}
		
		protected virtual void SendPropertyChanged(String propertyName)
		{
			if ((this.PropertyChanged != null))
			{
				this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.hoadon")]
	public partial class hoadon : INotifyPropertyChanging, INotifyPropertyChanged
	{
		
		private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
		
		private string _mahd;
		
		private string _ky;
		
		private System.Nullable<System.DateTime> _tungay;
		
		private System.Nullable<System.DateTime> _denngay;
		
		private System.Nullable<int> _chisodau;
		
		private System.Nullable<int> _chisocuoi;
		
		private System.Nullable<decimal> _tongthanhtien;
		
		private System.Nullable<System.DateTime> _ngaylaphd;
		
		private bool _tinhtrang;
		
		private EntitySet<cthoadon> _cthoadons;
		
    #region Extensibility Method Definitions
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void OnmahdChanging(string value);
    partial void OnmahdChanged();
    partial void OnkyChanging(string value);
    partial void OnkyChanged();
    partial void OntungayChanging(System.Nullable<System.DateTime> value);
    partial void OntungayChanged();
    partial void OndenngayChanging(System.Nullable<System.DateTime> value);
    partial void OndenngayChanged();
    partial void OnchisodauChanging(System.Nullable<int> value);
    partial void OnchisodauChanged();
    partial void OnchisocuoiChanging(System.Nullable<int> value);
    partial void OnchisocuoiChanged();
    partial void OntongthanhtienChanging(System.Nullable<decimal> value);
    partial void OntongthanhtienChanged();
    partial void OnngaylaphdChanging(System.Nullable<System.DateTime> value);
    partial void OnngaylaphdChanged();
    partial void OntinhtrangChanging(bool value);
    partial void OntinhtrangChanged();
    #endregion
		
		public hoadon()
		{
			this._cthoadons = new EntitySet<cthoadon>(new Action<cthoadon>(this.attach_cthoadons), new Action<cthoadon>(this.detach_cthoadons));
			OnCreated();
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_mahd", DbType="VarChar(10) NOT NULL", CanBeNull=false, IsPrimaryKey=true)]
		public string mahd
		{
			get
			{
				return this._mahd;
			}
			set
			{
				if ((this._mahd != value))
				{
					this.OnmahdChanging(value);
					this.SendPropertyChanging();
					this._mahd = value;
					this.SendPropertyChanged("mahd");
					this.OnmahdChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_ky", DbType="VarChar(7)")]
		public string ky
		{
			get
			{
				return this._ky;
			}
			set
			{
				if ((this._ky != value))
				{
					this.OnkyChanging(value);
					this.SendPropertyChanging();
					this._ky = value;
					this.SendPropertyChanged("ky");
					this.OnkyChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_tungay", DbType="DateTime")]
		public System.Nullable<System.DateTime> tungay
		{
			get
			{
				return this._tungay;
			}
			set
			{
				if ((this._tungay != value))
				{
					this.OntungayChanging(value);
					this.SendPropertyChanging();
					this._tungay = value;
					this.SendPropertyChanged("tungay");
					this.OntungayChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_denngay", DbType="DateTime")]
		public System.Nullable<System.DateTime> denngay
		{
			get
			{
				return this._denngay;
			}
			set
			{
				if ((this._denngay != value))
				{
					this.OndenngayChanging(value);
					this.SendPropertyChanging();
					this._denngay = value;
					this.SendPropertyChanged("denngay");
					this.OndenngayChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_chisodau", DbType="Int")]
		public System.Nullable<int> chisodau
		{
			get
			{
				return this._chisodau;
			}
			set
			{
				if ((this._chisodau != value))
				{
					this.OnchisodauChanging(value);
					this.SendPropertyChanging();
					this._chisodau = value;
					this.SendPropertyChanged("chisodau");
					this.OnchisodauChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_chisocuoi", DbType="Int")]
		public System.Nullable<int> chisocuoi
		{
			get
			{
				return this._chisocuoi;
			}
			set
			{
				if ((this._chisocuoi != value))
				{
					this.OnchisocuoiChanging(value);
					this.SendPropertyChanging();
					this._chisocuoi = value;
					this.SendPropertyChanged("chisocuoi");
					this.OnchisocuoiChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_tongthanhtien", DbType="Money")]
		public System.Nullable<decimal> tongthanhtien
		{
			get
			{
				return this._tongthanhtien;
			}
			set
			{
				if ((this._tongthanhtien != value))
				{
					this.OntongthanhtienChanging(value);
					this.SendPropertyChanging();
					this._tongthanhtien = value;
					this.SendPropertyChanged("tongthanhtien");
					this.OntongthanhtienChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_ngaylaphd", DbType="DateTime")]
		public System.Nullable<System.DateTime> ngaylaphd
		{
			get
			{
				return this._ngaylaphd;
			}
			set
			{
				if ((this._ngaylaphd != value))
				{
					this.OnngaylaphdChanging(value);
					this.SendPropertyChanging();
					this._ngaylaphd = value;
					this.SendPropertyChanged("ngaylaphd");
					this.OnngaylaphdChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_tinhtrang", DbType="Bit NOT NULL")]
		public bool tinhtrang
		{
			get
			{
				return this._tinhtrang;
			}
			set
			{
				if ((this._tinhtrang != value))
				{
					this.OntinhtrangChanging(value);
					this.SendPropertyChanging();
					this._tinhtrang = value;
					this.SendPropertyChanged("tinhtrang");
					this.OntinhtrangChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="hoadon_cthoadon", Storage="_cthoadons", ThisKey="mahd", OtherKey="mahd")]
		public EntitySet<cthoadon> cthoadons
		{
			get
			{
				return this._cthoadons;
			}
			set
			{
				this._cthoadons.Assign(value);
			}
		}
		
		public event PropertyChangingEventHandler PropertyChanging;
		
		public event PropertyChangedEventHandler PropertyChanged;
		
		protected virtual void SendPropertyChanging()
		{
			if ((this.PropertyChanging != null))
			{
				this.PropertyChanging(this, emptyChangingEventArgs);
			}
		}
		
		protected virtual void SendPropertyChanged(String propertyName)
		{
			if ((this.PropertyChanged != null))
			{
				this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
			}
		}
		
		private void attach_cthoadons(cthoadon entity)
		{
			this.SendPropertyChanging();
			entity.hoadon = this;
		}
		
		private void detach_cthoadons(cthoadon entity)
		{
			this.SendPropertyChanging();
			entity.hoadon = null;
		}
	}
	
	public partial class getDSKHChuaDongTienResult
	{
		
		private string _makh;
		
		private string _tenkh;
		
		private string _diachi;
		
		private string _dt;
		
		private string _cmnd;
		
		private string _madk;
		
		private string _makh1;
		
		private System.Nullable<System.DateTime> _ngaysx;
		
		private System.Nullable<System.DateTime> _ngaylap;
		
		private string _mota;
		
		private System.Nullable<bool> _trangthai;
		
		private string _mahd;
		
		private string _madk1;
		
		private System.Nullable<int> _dntt;
		
		private System.Nullable<decimal> _dongia;
		
		private string _mahd1;
		
		private string _ky;
		
		private System.Nullable<System.DateTime> _tungay;
		
		private System.Nullable<System.DateTime> _denngay;
		
		private System.Nullable<int> _chisodau;
		
		private System.Nullable<int> _chisocuoi;
		
		private System.Nullable<decimal> _tongthanhtien;
		
		private System.Nullable<System.DateTime> _ngaylaphd;
		
		private System.Nullable<bool> _tinhtrang;
		
		public getDSKHChuaDongTienResult()
		{
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_makh", DbType="VarChar(13) NOT NULL", CanBeNull=false)]
		public string makh
		{
			get
			{
				return this._makh;
			}
			set
			{
				if ((this._makh != value))
				{
					this._makh = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_tenkh", DbType="NVarChar(50)")]
		public string tenkh
		{
			get
			{
				return this._tenkh;
			}
			set
			{
				if ((this._tenkh != value))
				{
					this._tenkh = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_diachi", DbType="NVarChar(100)")]
		public string diachi
		{
			get
			{
				return this._diachi;
			}
			set
			{
				if ((this._diachi != value))
				{
					this._diachi = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_dt", DbType="NVarChar(12)")]
		public string dt
		{
			get
			{
				return this._dt;
			}
			set
			{
				if ((this._dt != value))
				{
					this._dt = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_cmnd", DbType="VarChar(9)")]
		public string cmnd
		{
			get
			{
				return this._cmnd;
			}
			set
			{
				if ((this._cmnd != value))
				{
					this._cmnd = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_madk", DbType="VarChar(8)")]
		public string madk
		{
			get
			{
				return this._madk;
			}
			set
			{
				if ((this._madk != value))
				{
					this._madk = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_makh1", DbType="VarChar(13)")]
		public string makh1
		{
			get
			{
				return this._makh1;
			}
			set
			{
				if ((this._makh1 != value))
				{
					this._makh1 = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_ngaysx", DbType="DateTime")]
		public System.Nullable<System.DateTime> ngaysx
		{
			get
			{
				return this._ngaysx;
			}
			set
			{
				if ((this._ngaysx != value))
				{
					this._ngaysx = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_ngaylap", DbType="DateTime")]
		public System.Nullable<System.DateTime> ngaylap
		{
			get
			{
				return this._ngaylap;
			}
			set
			{
				if ((this._ngaylap != value))
				{
					this._ngaylap = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_mota", DbType="NVarChar(100)")]
		public string mota
		{
			get
			{
				return this._mota;
			}
			set
			{
				if ((this._mota != value))
				{
					this._mota = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_trangthai", DbType="Bit")]
		public System.Nullable<bool> trangthai
		{
			get
			{
				return this._trangthai;
			}
			set
			{
				if ((this._trangthai != value))
				{
					this._trangthai = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_mahd", DbType="VarChar(10)")]
		public string mahd
		{
			get
			{
				return this._mahd;
			}
			set
			{
				if ((this._mahd != value))
				{
					this._mahd = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_madk1", DbType="VarChar(8)")]
		public string madk1
		{
			get
			{
				return this._madk1;
			}
			set
			{
				if ((this._madk1 != value))
				{
					this._madk1 = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_dntt", DbType="Int")]
		public System.Nullable<int> dntt
		{
			get
			{
				return this._dntt;
			}
			set
			{
				if ((this._dntt != value))
				{
					this._dntt = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_dongia", DbType="Money")]
		public System.Nullable<decimal> dongia
		{
			get
			{
				return this._dongia;
			}
			set
			{
				if ((this._dongia != value))
				{
					this._dongia = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_mahd1", DbType="VarChar(10)")]
		public string mahd1
		{
			get
			{
				return this._mahd1;
			}
			set
			{
				if ((this._mahd1 != value))
				{
					this._mahd1 = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_ky", DbType="VarChar(7)")]
		public string ky
		{
			get
			{
				return this._ky;
			}
			set
			{
				if ((this._ky != value))
				{
					this._ky = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_tungay", DbType="DateTime")]
		public System.Nullable<System.DateTime> tungay
		{
			get
			{
				return this._tungay;
			}
			set
			{
				if ((this._tungay != value))
				{
					this._tungay = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_denngay", DbType="DateTime")]
		public System.Nullable<System.DateTime> denngay
		{
			get
			{
				return this._denngay;
			}
			set
			{
				if ((this._denngay != value))
				{
					this._denngay = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_chisodau", DbType="Int")]
		public System.Nullable<int> chisodau
		{
			get
			{
				return this._chisodau;
			}
			set
			{
				if ((this._chisodau != value))
				{
					this._chisodau = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_chisocuoi", DbType="Int")]
		public System.Nullable<int> chisocuoi
		{
			get
			{
				return this._chisocuoi;
			}
			set
			{
				if ((this._chisocuoi != value))
				{
					this._chisocuoi = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_tongthanhtien", DbType="Money")]
		public System.Nullable<decimal> tongthanhtien
		{
			get
			{
				return this._tongthanhtien;
			}
			set
			{
				if ((this._tongthanhtien != value))
				{
					this._tongthanhtien = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_ngaylaphd", DbType="DateTime")]
		public System.Nullable<System.DateTime> ngaylaphd
		{
			get
			{
				return this._ngaylaphd;
			}
			set
			{
				if ((this._ngaylaphd != value))
				{
					this._ngaylaphd = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_tinhtrang", DbType="Bit")]
		public System.Nullable<bool> tinhtrang
		{
			get
			{
				return this._tinhtrang;
			}
			set
			{
				if ((this._tinhtrang != value))
				{
					this._tinhtrang = value;
				}
			}
		}
	}
}
#pragma warning restore 1591
